# This file was generated by GoReleaser. DO NOT EDIT.
class TelepresenceLauncher < Formula
  desc "telepresence-launcher provides a guided interface to replace a Kubernetes deployment in an established K8s context in a consistent manner using Telepresence."
  homepage "https://github.com/aaa-ncnu/telepresence-launcher"
  url "https://github.com/aaa-ncnu/telepresence-launcher/releases/download/v0.2.1/telepresence-launcher_0.2.1_MacOS_x86_64.tar.gz"
  version "0.2.1"
  sha256 "0bcc3fe9302bd3bedd4b5c1c55538c4977c72b7d76c727e39fb2be0a7c5ac8b4"

  def install
    bin.install "telepresence-launcher"
  end
end
